# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: franciscojsc/conversao-peso:v1
          ports:
            - containerPort: 80

---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort
