# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-conversao-peso
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-conversao-peso
  template:
    metadata:
      labels:
        app: web-conversao-peso
    spec:
      containers:
        - name: conatainer-conversao-peso
          image: franciscojsc/conversao-peso:v1
          ports:
            - containerPort: 80

---
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: service-conversao-peso
spec:
  selector:
    app: web-conversao-peso
  ports:
    - port: 80
  type: LoadBalancer
