name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: |
            franciscojsc/conversao-ṕeso:latest
            franciscojsc/conversao-peso:v${{ github.run_number }}
        
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v2
      - name: Azure Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Deploy Web
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: franciscojsc/conversao-peso:v${{ github.run_number }}
  
